version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.12-node-browsers
    working_directory: /go/src/github.com/fergusstrange/roundofbeer
    environment:
      GO111MODULE: "on"
      CI: "true"
jobs:
  build:
    executor: default
    steps:
    - checkout
    - run: |
        curl -sf https://up.apex.sh/install | sudo sh && \
        sudo npm install -g yarn && \
        go get -u github.com/mattn/goveralls
    - run: |
        if [ ! -d "/home/circleci/pact" ]; then
          curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | bash
          mv pact /home/circleci/pact
        fi
    - run: |
        export PATH=/home/circleci/bin:/home/circleci/pact/bin:$PATH && \
        pushd ui && \
        rm -rf build && \
        yarn && \
        yarn test && \
        yarn feature-test && \
        yarn build && \
        rm -rf node_modules && \
        popd && \
        pushd api && \
        sed -i -e 's/$SIGNING_KEY_REPLACE/'${SIGNING_KEY}'/g' up.json && \
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.17.1 && \
        golangci-lint run --issues-exit-code 1 --enable golint --enable gofmt ./... && \
        go test -v -cover -race -coverprofile=coverage.out ./... && \
        goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN && \
        GOOS=linux GOARCH=amd64 go build -o server *.go && \
        popd
    - store_artifacts:
        path: /go/src/github.com/fergusstrange/roundofbeer/api/handlers/.sequence
        destination: api-sequence-diagrams

    - persist_to_workspace:
        root: /go/src/github.com/fergusstrange
        paths:
        - roundofbeer

  deploy-to-staging:
    executor: default
    steps:
    - attach_workspace:
        at: /go/src/github.com/fergusstrange
    - run: |
        curl -sf https://up.apex.sh/install | sudo sh && \
        up deploy staging --chdir api --verbose && \
        up deploy staging --chdir ui --verbose

  deploy-to-prod:
    executor: default
    steps:
    - attach_workspace:
        at: /go/src/github.com/fergusstrange
    - run: |
        curl -sf https://up.apex.sh/install | sudo sh && \
        up deploy production --chdir api --verbose && \
        up deploy production --chdir ui --verbose

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        context: home-build
        filters:
          branches:
            only:
            - master
    - deploy-to-staging:
        context: home-aws
        requires:
        - build
    - deploy-to-prod-approval:
        type: approval
        requires:
        - deploy-to-staging
    - deploy-to-prod:
        context: home-aws
        requires:
        - deploy-to-prod-approval
