version: 2
jobs:
  build:
    working_directory: /go/src/github.com/fergusstrange/roundofbeer
    docker:
      - image: circleci/golang:1.12-node
        environment:
          GO111MODULE: "on"
          CI: "true"
    steps:
      - checkout
      - run: |
          curl -sf https://up.apex.sh/install | sudo sh && \
          sudo npm install -g yarn
      - run: |
          if [ ! -d "/home/circleci/pact" ]; then
            curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | bash
            mv pact /home/circleci/pact
          fi
      - run: |
          export PATH=/home/circleci/bin:/home/circleci/pact/bin:$PATH && \
          pushd ui && \
          rm -rf build && \
          yarn && \
          yarn test && \
          yarn build && \
          popd && \
          pushd api && \
          sed -i -e 's/$SIGNING_KEY_REPLACE/'${SIGNING_KEY}'/g' up.json && \
          go test -v ./... && \
          popd && \
          up deploy production --chdir api && \
          up deploy production --chdir ui
