version: 2
jobs:
  build:
    working_directory: /go/src/github.com/fergusstrange/roundofbeer
    docker:
      - image: circleci/golang:1.12-node
        environment:
          GO111MODULE: "on"
          CI: "true"
    steps:
      - checkout
      - run: |
          curl -sf https://up.apex.sh/install | sudo sh && \
          sudo npm install -g yarn
      - run: |
          pushd api && \
          go test -v ./... && \
          popd && \
          up deploy production --chdir api && \
          pushd ui && \
          rm -rf build && \
          yarn && yarn build && \
          popd && \
          up deploy production --chdir ui